-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 23:50:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facechamp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `facechamp` ;

-- -----------------------------------------------------
-- Schema facechamp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facechamp` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `facechamp` ;

-- -----------------------------------------------------
-- Table `facechamp`.`cfg_client_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`cfg_client_type` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_CLIENT_TYPE_NAME` (`name` ASC))
ENGINE = InnoDB
COMMENT = '`facechamp.domain.ClientType`';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`user_account` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_type` INT UNSIGNED NOT NULL,
  `hw_id` VARCHAR(127) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `create_utc` BIGINT(19) NULL,
  `update_utc` BIGINT(19) NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_ACCOUNT_DEVICE` (`client_type` ASC, `hw_id` ASC),
  UNIQUE INDEX `UQ_ACCOUNT_USERNAME` (`username` ASC),
  CONSTRAINT `FK_ACCOUNT_PK_CLIENT_TYPE`
    FOREIGN KEY (`client_type`)
    REFERENCES `facechamp`.`cfg_client_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`audit_user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`audit_user_account` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dml` ENUM('U', 'D') NOT NULL COMMENT 'CRUD',
  `account` INT(9) UNSIGNED NOT NULL COMMENT 'user_account.id',
  `client_type` INT UNSIGNED NOT NULL COMMENT 'user_account.client_type',
  `hw_id` VARCHAR(127) NOT NULL COMMENT 'user_account.hw_id',
  `username` VARCHAR(45) NOT NULL COMMENT 'user_account.username',
  `create_utc` BIGINT(19) NOT NULL COMMENT 'user_account.create_utc',
  `update_utc` BIGINT(19) NOT NULL COMMENT 'user_account.update_utc',
  `modify_ts` TIMESTAMP NOT NULL COMMENT 'user_account.modify_ts',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'audit log of `user_account`';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`cfg_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`cfg_language` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_LANGUAGE_NAME` (`name` ASC))
ENGINE = InnoDB
COMMENT = '`facechamp.domain.Language`';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`cfg_text_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`cfg_text_type` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_TEXT_TYPE_NAME` (`name` ASC))
ENGINE = InnoDB
COMMENT = '`facechamp.domain.TextType`';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`master_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`master_text` (
  `text_type` INT UNSIGNED NOT NULL,
  `language` INT UNSIGNED NOT NULL,
  `message` TEXT NOT NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`text_type`, `language`),
  INDEX `FK_TEXT_PK_TEXT_TYPE` (`language` ASC),
  CONSTRAINT `FK_TEXT_PK_TEXT_TYPE`
    FOREIGN KEY (`text_type`)
    REFERENCES `facechamp`.`cfg_text_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TEXT_PK_LANGUAGE`
    FOREIGN KEY (`language`)
    REFERENCES `facechamp`.`cfg_language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`audit_master_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`audit_master_text` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dml` ENUM('U', 'D') NOT NULL COMMENT 'CRUD',
  `text_type` INT UNSIGNED NOT NULL COMMENT '	',
  `language` INT UNSIGNED NOT NULL,
  `message` TEXT NOT NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`user_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`user_player` (
  `id` INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner` INT(9) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PLAYER_OWNER` (`owner` ASC),
  CONSTRAINT `FK_PLAYER_OWNER`
    FOREIGN KEY (`owner`)
    REFERENCES `facechamp`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`user_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`user_tag` (
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`rel_player_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`rel_player_tag` (
  `player` INT(9) UNSIGNED NOT NULL,
  `tag` VARCHAR(32) NOT NULL,
  INDEX `REL_PLAYER_TAG` (`tag` ASC),
  PRIMARY KEY (`player`, `tag`),
  CONSTRAINT `REL_TAG_PLAYER`
    FOREIGN KEY (`player`)
    REFERENCES `facechamp`.`user_player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `REL_PLAYER_TAG`
    FOREIGN KEY (`tag`)
    REFERENCES `facechamp`.`user_tag` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
USE `facechamp`;

DELIMITER $$
SHOW WARNINGS$$
USE `facechamp`$$
CREATE TRIGGER `facechamp`.`audit_user_account_update` AFTER UPDATE ON `user_account`
FOR EACH ROW BEGIN
  INSERT INTO `audit_user_account`(`dml`, `account`, `client_type`, `hw_id`, `username`, `create_utc`, `update_utc`)
  VALUES ('U', OLD.`id`, OLD.`client_type`, OLD.`hw_id`, OLD.`username`, OLD.`create_utc`, OLD.`update_utc`);
END;$$

SHOW WARNINGS$$
SHOW WARNINGS$$
USE `facechamp`$$
CREATE TRIGGER `facechamp`.`audit_user_account_delete` AFTER DELETE ON `user_account`
FOR EACH ROW BEGIN
  INSERT INTO `audit_user_account`(`dml`, `account`, `client_type`, `hw_id`, `username`, `create_utc`, `update_utc`)
  VALUES ('D', OLD.`id`, OLD.`client_type`, OLD.`hw_id`, OLD.`username`, OLD.`create_utc`, OLD.`update_utc`);
END$$

SHOW WARNINGS$$
SHOW WARNINGS$$
USE `facechamp`$$
CREATE TRIGGER `facechamp`.`audit_master_text_update` AFTER UPDATE ON `master_text`
FOR EACH ROW BEGIN
	INSERT INTO `audit_master_text`(`dml`, `text_type`, `language`, `message`, `create_utc`, `update_utc`)
    VALUES ('U', OLD.`text_type`, OLD.`language`, OLD.`message`, OLD.`create_utc`, OLD.`update_utc`);
END$$

SHOW WARNINGS$$
SHOW WARNINGS$$
USE `facechamp`$$
CREATE TRIGGER `facechamp`.`audit_master_text_delete` AFTER DELETE ON `master_text`
FOR EACH ROW BEGIN
	INSERT INTO `audit_master_text`(`dml`, `text_type`, `language`, `message`, `create_utc`, `update_utc`)
    VALUES ('D', OLD.`text_type`, OLD.`language`, OLD.`message`, OLD.`create_utc`, OLD.`update_utc`);
END$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `facechamp`.`cfg_client_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `facechamp`;
INSERT INTO `facechamp`.`cfg_client_type` (`id`, `name`, `description`, `modify_ts`) VALUES (0, 'WIN', 'Microsoft Windows', DEFAULT);
INSERT INTO `facechamp`.`cfg_client_type` (`id`, `name`, `description`, `modify_ts`) VALUES (1, 'IOS', 'Apple iOS', DEFAULT);
INSERT INTO `facechamp`.`cfg_client_type` (`id`, `name`, `description`, `modify_ts`) VALUES (2, 'ANDROID', 'Google Android', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `facechamp`.`cfg_language`
-- -----------------------------------------------------
START TRANSACTION;
USE `facechamp`;
INSERT INTO `facechamp`.`cfg_language` (`id`, `name`, `description`, `modify_ts`) VALUES (0, 'KO', '한국어', DEFAULT);
INSERT INTO `facechamp`.`cfg_language` (`id`, `name`, `description`, `modify_ts`) VALUES (1, 'JA', '日本語', DEFAULT);
INSERT INTO `facechamp`.`cfg_language` (`id`, `name`, `description`, `modify_ts`) VALUES (2, 'EN', 'English', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `facechamp`.`cfg_text_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `facechamp`;
INSERT INTO `facechamp`.`cfg_text_type` (`id`, `name`, `description`, `modify_ts`) VALUES (0, 'PRESET_ACCOUNT_USERNAME', '계정 생성시의 기본 이름.', DEFAULT);

COMMIT;

