-- MySQL Script generated by MySQL Workbench
-- Fri Aug 26 21:06:44 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facechamp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `facechamp` ;

-- -----------------------------------------------------
-- Schema facechamp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facechamp` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
SHOW WARNINGS;
USE `facechamp` ;

-- -----------------------------------------------------
-- Table `facechamp`.`cfg_client_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`cfg_client_type` (
  `pk` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `UQ_CLIENT_TYPE_NAME` (`name` ASC))
ENGINE = InnoDB
COMMENT = '이 테이블은 엔티티 인스턴스로 변환되지 않는다. `enum facechamp.domain.ClientType`에서 선언한 변수만 사용할 수 있도록, DB 수준에서 제약을 거는 용도.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `facechamp`.`user_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facechamp`.`user_device` (
  `pk` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dev_key` BIGINT UNSIGNED NOT NULL,
  `client_type` INT UNSIGNED NOT NULL,
  `identifier` VARCHAR(255) NOT NULL,
  `create_utc` BIGINT NOT NULL,
  `update_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
  UNIQUE INDEX `UQ_DEVICE_IDENTIFIER` (`client_type` ASC, `identifier` ASC),
  UNIQUE INDEX `UQ_DEV_KEY` (`dev_key` ASC),
  CONSTRAINT `FK_DEVICE_PK_CLIENT_TYPE`
    FOREIGN KEY (`client_type`)
    REFERENCES `facechamp`.`cfg_client_type` (`pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `facechamp`.`cfg_client_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `facechamp`;
INSERT INTO `facechamp`.`cfg_client_type` (`pk`, `name`, `description`, `modify_ts`) VALUES (0, 'WIN', 'Microsoft Windows', DEFAULT);
INSERT INTO `facechamp`.`cfg_client_type` (`pk`, `name`, `description`, `modify_ts`) VALUES (1, 'IOS', 'Apple iOS', DEFAULT);
INSERT INTO `facechamp`.`cfg_client_type` (`pk`, `name`, `description`, `modify_ts`) VALUES (2, 'ANDROID', 'Google Android', DEFAULT);

COMMIT;

